parameters:
    task.sendmail.class: ITER\NameBundle\Model\SendMail

services:
    listener.email_confirmation_listener:
        class: Rebeca\TaskBundle\EventListener\EmailConfirmationListener
        arguments: [ @logger, @mailer, @service_container]
        tags:
            - { name: kernel.event_listener, event: task_bundle.create.confirmation, method: onConfirmationSuccess }

